root = "."
testdata_dir = ".testdata"
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./.tmp/main"
  cmd = "cd ./internal/ui/src/ && npx tailwindcss -i ./css/main.css -o ./css/output.css && cd ../../../  && go build -o ./.tmp/main ./cmd/run"
  delay = 1000
  exclude_dir = ["assets", ".tmp", "vendor", ".testdata", "internal/ui/src/node_modules"]
  exclude_file = ["internal/ui/src/css/output.css"]
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "gohtml", "js", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false


